spring.application.name=Cyber Cafe Management System
spring.datasource.url=jdbc:mysql://localhost:3306/cybercafe
spring.datasource.username=cybercafe_user
spring.datasource.password=StrongPassword123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true